# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='gname',
            name='medkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapi.medicine'),
        ),
        migrations.AddField(
            model_name='bname',
            name='medkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapi.medicine'),
        ),
    ]
